### PR TITLE
Data version control

### PR DESCRIPTION
**Pull request by RodinHaker**
Added a DVC pipeline to the repo.
Also created a README with instructions. Refer to that for how to run the code.
Some small restructuring has been done, see section `Project structure` in the README.

### CODE REVIEW

**Comment by tpenning** [comment]
I'm getting an error when trying to get the data. Running `dvc repro` gives an error. Rewriting it to `./dvc.yaml repro` seems better but still gets stuck.

**Comment by tpenning** [comment]
> I'm getting an error when trying to get the data. Running `dvc repro` gives an error. Rewriting it to `./dvc.yaml repro` seems better but still gets stuck.

The problem probably had to do with other programs open on my device or my impatience as it runs fine now, however, it still only accepts the rewritten version. `./dvc.yaml repro`

**Comment by MrsHan23** [comment]
I'm getting the following error when running `dvc repro`:

image

**Comment by tpenning** [comment]
The pretrained model command also gives a problem:
(Also I had to rewrite the command to use `python` instead of `python3` on my end
image

**Comment by tpenning** [comment]
> I'm getting the following error when running `dvc repro`:
> 
> image

Before my attempts might not have used the environment in the best way, but with a proper shell I have this same problem when running that command.

**Comment by RodinHaker** [comment]
> The pretrained model command also gives a problem related to a dvc file: (Also I had to rewrite the command to use `python` instead of `python3` on my end image

I have fixed this issue in the newest commit

**Comment by RodinHaker** [comment]
> I'm getting the following error when running `dvc repro`:
> 
> image

This error should be resolved with the latest commit

**Comment by ahasami** [comment]
in get_data.py:
file.name.split('.')[0].split("/")[2] does not work properly when on windows.

s3.download_file(bucket_name, file_name, output_file) does not work without credentials? even though it should

**Comment by tpenning** [comment]
The tensorflow package did not install properly on windows, adding the tensorflow-intel for Windows devices this issue was fixed.

**Comment by tpenning** [comment]
> The tensorflow package did not install properly on windows, adding the tensorflow-intel for Windows devices this issue was fixed.

Maybe we should add this for MacOS too just in case

**Comment by tpenning** [comment]
The pathing on Windows devices was also fixed, but should perhaps be moved into some initialization

**Review by tpenning — APPROVED** [review]
All the running problems were mentioned in the comments on the merge request and fixed in the various commits. The code works now and can be merged.

**Pull request merged**
